version: '3.8'

services:
  app:
    container_name: matcha-app
    image: 555622622153.dkr.ecr.ap-southeast-1.amazonaws.com/matcha-app:latest
    restart: unless-stopped
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    # Memory limits to work well on t3.micro
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
networks:
  app-network:
    driver: bridge 